# ff.yaml
# This .yaml file contains all configuration info required by the ffd engine.
input:
    salaries:
        filename: /Users/jcalizo/Devel/ffd/in/fanduel_data.csv
        type: fanduel
    stats:
        Base Projection:
            filename: /Users/jcalizo/Devel/ffd/in/fantasypros_data.csv
            type: fantasypros
#            filename: /Users/jcalizo/Devel/ffd/in/fanduel_data.csv
#            type: fanduel
        Injury Status:
            filename: /Users/jcalizo/Devel/ffd/in/fanduel_data.csv
            type: fanduel
filters:
    QB:
        min: 5500
        max: 12000
        exclude_injury:
            probable: 0
            doutful: 1
            questionable: 1
            out: 1
            injured_reserve: 1
        output:
            min_base_projected: 0
            min_base_ppd: 0
            min_modeled_projected: 15
            min_modeled_ppd: 0.002
    RB:
        min: 5000
        max: 10000
        exclude_injury:
            probable: 0
            doutful: 1
            questionable: 1
            out: 1
            injured_reserve: 1
        output:
            min_base_projected: 0
            min_base_ppd: 0
            min_modeled_projected: 10
            min_modeled_ppd: 0.002
    WR:
        min: 5000
        max: 10000
        exclude_injury:
            probable: 0
            doutful: 1
            questionable: 1
            out: 1
            injured_reserve: 1
        output:
            min_base_projected: 0
            min_base_ppd: 0
            min_modeled_projected: 10
            min_modeled_ppd: 0.0021
    TE:
        min: 2000
        max: 10000
        exclude_injury:
            probable: 0
            doutful: 1
            questionable: 1
            out: 1
            injured_reserve: 1
        output:
            min_base_projected: 0
            min_base_ppd: 0
            min_modeled_projected: 4
            min_modeled_ppd: 0.0022
    K:
        min: 3000
        max: 5500
        exclude_injury:
            probable: 0
            doutful: 1
            questionable: 1
            out: 1
            injured_reserve: 1
        output:
            min_base_projected: 0
            min_base_ppd: 0
            min_modeled_projected: 6
            min_modeled_ppd: 0.0015
    D:
        min: 3000
        max: 5500
        exclude_injury:
            probable: 0
            doutful: 1
            questionable: 1
            out: 1
            injured_reserve: 1
        output:
            min_base_projected: 0
            min_base_ppd: 0
            min_modeled_projected: 0
            min_modeled_ppd: 0
rules:
    lineup:
        QB:
            count: 1
        RB:
            count: 2
        WR:
            count: 3
        TE:
            count: 1
        K:
            count: 1
        D:
            count: 1
    cap: 60000
models:
    single:
        Position:
            RB:
                b1: 1.113
                b0: 1.062
            TE:
                b1: 1.918
                b0: -0.656
            WR:
                b1: 1.422
                b0: 1.072
    team:
anal:
    max_lineups: 100
    top_lineups: 5